### ISSUE TITLE
Repeatedly plotting in an IJulia notebook spams the "GKS: invalid workstation type" warning

### ISSUE THREAD

**Issue by Paveloom** [heliosdrm/GRUtils.jl#101]
![1](https://user-images.githubusercontent.com/49961859/130499321-7ed81926-4ac1-4eba-a616-103b0c3d63dc.png)
![2](https://user-images.githubusercontent.com/49961859/130499323-4af352d7-55f5-4c17-8b2d-973865b40d1b.png)
![3](https://user-images.githubusercontent.com/49961859/130499328-4824a01b-8a68-4d4e-8ca8-f5282a42cd62.png)

The message gets bigger with every call, and the image scaling gets broken after the first plot.

Versions:
Julia: 1.6.2
IJulia: 1.23.2
GRUtils: 0.6.2

**Comment by heliosdrm** [comment]
I don't know what is the source of this problem. Can you try if this issue disappears with GRUtils 0.6.3, which can be used with newer versions of GR.jl?

**Comment by Paveloom** [comment]
Yep, seems to be fixed now.

Versions:
Julia: 1.7.1
IJulia: 1.23.2
GRUtils: 0.6.3
