### ISSUE TITLE
Possible to set linewidth?

### ISSUE THREAD

**Issue by ericphanson** [heliosdrm/GRUtils.jl#28]
This package is great! Really fast frontend to GR with good documentation. I couldn't find how to set the linewidth however; is that possible?

**Comment by heliosdrm** [comment]
Thanks for sending the issue.

This is not (yet) available in the current release (0.2.0), but it is implemented in master now, and will be available in the next version (0.2.1) soon, together with many other improvements: configurable marker size, user-defined colors for lines, markers, bars, and easy selection of colormaps and color schemes, among other things.

(Note: the selection of colormaps and schemes is also available in vanilla GR, but not documented).

**Comment by heliosdrm** [comment]
Until the new version is ready with its documentation, if you want to checkout the master branch and test, you may try:

```julia
plot(x, y, linewidth=2)
```

**Comment by ericphanson** [comment]
Great, thanks!

**Comment by heliosdrm** [comment]
version 0.3.0 is about to be registered with those updates.
