### ISSUE TITLE
interfaces for `imshow`

### ISSUE THREAD

**Issue by heliosdrm** [heliosdrm/GRUtils.jl#53]
Currently supported inputs are:

* An image file
* A matrix with values in the range [0-1]

The following options could be added:

* Accept RGB(A) arrays (n×m×3 or n×m×4) with values in the range [0-1].
* Normalization of input values.

Python uses a keyword argument to set if values are to be normalized; Matlab/Octave allows to set the limits for normalization (with empty limits for automatic normalization). @jheinen: which approach do you prefer?

**Comment by jheinen** [comment]
I think we should, if possible, make everything MATLAB compliant.

**Comment by heliosdrm** [comment]
Ok, so `imshow` should accept a second (optional) positional argument, with the lower and upper values that will be mapped to the colormap. I'll add that option.

Regarding the automatic calculation of limits, I like how they are set for `xlim`, etc. in GR, so we could use the same logic for `imshow`: use `(minval, maxval)` to set the lower and upper bounds as arbitrary values, and replace any of them by `nothing` if you want it to match the minimum or maximum value of the data.
