### ISSUE TITLE
Integration with VSCode / Juno?

### ISSUE THREAD

**Issue by dpo** [heliosdrm/GRUtils.jl#70]
If I use plain GR, plots open in a VSCode tab, but if I use GRUtils, they open in a separate window. Are there any plans to integrate GRUtils with VSCode/Juno?

**Comment by heliosdrm** [comment]
GRUtils should do the same as GR in this regard. Can you tell what versions of GR and GRUtils are you comparing? In this moment GRUtils supports up to GR 0.51, because when tried to add the latest version (GR 0.52) some errors started to happen - still to be solved, I hope soon.

**Comment by heliosdrm** [comment]
Hi, I think this was solved time ago, so I close it. Feel free to re-open if there is anything that I missed.
