### ISSUE TITLE
`yflip` moves the x-tick-labels to overlay the `title`.

### ISSUE THREAD

**Issue by kapple19** [heliosdrm/GRUtils.jl#74]
This code
```julia
using GRUtils
x = 1:10
y = x.^2
f = Figure()
plot!(f, x, y)
yflip!(f, true)
title!(f, "A Parabola")
display(f)
```
demonstrates the x-tick-labels overlaying the title.

Is this a bug? Must I manually move the x-tick-labels below the plot where I desire them to be?

**Comment by heliosdrm** [comment]
Yes, it is a bug, the axis tick-labels should  stay on bottom. Thanks for noting.

**Comment by kapple19** [comment]
Glad to (hopefully) help. =)
