### ISSUE TITLE
`heatmap` displaying confusing output and accepts strange inputs

### ISSUE THREAD

**Issue by kapple19** [heliosdrm/GRUtils.jl#75]
The following code

```julia
julia> x = 1:0.5:10;  y = 1:0.25:5; z = x'.*y;

julia> using GRUtils

julia> heatmap(x, y, z)
```

yields the following heatmap

![image](https://user-images.githubusercontent.com/48305293/98108791-aa1ddc00-1ef0-11eb-829a-d24a6d3eda47.png)

and appending the code with 
```julia
julia> z = x.*y'

julia> heatmap(x, y, z)
```

yields the following heatmap

![image](https://user-images.githubusercontent.com/48305293/98108868-c9b50480-1ef0-11eb-881f-0fa664e33110.png)

I have a few questions:
1. I know the right way is the first way (`z = x'.*y`), but why does `heatmap` accept `z = x.*y'` as well, when it's a different size array?
2. Why is there a diagonal discontinuity?

Even scarier, `heatmap` accepts completely inconsistent sizes.

```julia
julia> heatmap([1, 2, 3, 4], [5, 6, 7, 8, 9, 10], [1 2; 3 4])
```

![image](https://user-images.githubusercontent.com/48305293/98109307-755e5480-1ef1-11eb-833a-32ee0705792e.png)

Is the `heatmap` just still a WIP? Or is there some rationale behind this functionality?

**Comment by heliosdrm** [comment]
No, it may be considered a bug. Thanks for reporting.
