### ISSUE TITLE
adding annotations removes tick labels

### ISSUE THREAD

**Issue by ericphanson** [heliosdrm/GRUtils.jl#88]
E.g.
```julia
using GRUtils
labels = string.('a':'f')
vals = rand(6)*10
barplot(labels, vals)
```
![testplt](https://user-images.githubusercontent.com/5846501/108612457-3f35d980-73e9-11eb-8b72-1072e005a984.png)

Looks fine, but if we add annotations:
```julia
annotations(1:6, vals .+1, string.(round.(vals; digits=2)), halign="center")
```
![testplt_annotations](https://user-images.githubusercontent.com/5846501/108612458-43fa8d80-73e9-11eb-983d-089996088374.png)

we lose every other tick label. We can fix it by `xticks(1)` though:

```julia
xticks(1)
```
![testplt_annotations_fixed](https://user-images.githubusercontent.com/5846501/108612461-46f57e00-73e9-11eb-90fe-9e260e262f76.png)

**Comment by heliosdrm** [comment]
Thanks for reporting. It should be fixed by #89, I hope.
